name: Docker Nightly

on:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build-and-push:
    uses: seiferma/build-utils/.github/workflows/build-dockerfile.yml@main
    with:
      registry-host: quay.io
      image-name: seiferma/caddy-lego
      platforms: linux/amd64,linux/arm64
      tag: stable
      build-args: |
        CADDY_VERSION=latest
    secrets:
      registry-user: seiferma+github
      registry-password: ${{ secrets.QUAY_TOKEN }}
