name: Docker Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build-and-push:
    uses: seiferma/build-utils/.github/workflows/build-dockerfile.yml@main
    with:
      registry-host: quay.io
      image-name: seiferma/caddy-lego
      platforms: linux/amd64,linux/arm64
      suppress-push: true
    secrets:
      registry-user: seiferma+github
      registry-password: ${{ secrets.QUAY_TOKEN }}
